version: "3.9"

services:
    dev-finder-app:
        container_name: dev-finder-app
        restart: always
        build:
            context: .
            dockerfile: Dockerfile
            target: development
        env_file:
            - .env
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
        depends_on:
            - dev-finder-db
        command: npm run dev
        volumes:
            - .:/app
            - /app/node_modules
            - /app/.next
        ports:
            - 3000:3000

    dev-finder-db:
        image: postgres
        restart: always
        container_name: dev-finder-db
        ports:
            - 5432:5432
        environment:
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_DB: ${DB_NAME}
            PGDATA: /data/postgres
        volumes:
            - postgres:/data/postgres

volumes:
    postgres:
